version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Windows Server 2012 R2
shallow_clone: true
build_script:
- cd "%APPVEYOR_BUILD_FOLDER%"
- cd standalone
- mkdir build
- mkdir output
- cd build
- cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\standalone\output" ../nowide
- msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild RUN_TESTS.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: .\standalone\output\
  name: nowide-lib
