version: 0.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Windows Server 2012 R2
shallow_clone: true
build_script:
- cd "%APPVEYOR_BUILD_FOLDER%"
- cd standalone
- mkdir build-dll
- mkdir build-lib
- mkdir output
- cd build-dll
- cmake -G "Visual Studio 12 2013 Win64" -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\standalone\output-msvc" ../nowide
- msbuild INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd ..\build-lib
- cmake -G "Visual Studio 12 2013 Win64" -DBUILD_SHARED_LIBS=OFF ../nowide
- msbuild ALL_BUILD.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cp Debug\nowide0.lib ..\output\lib\nowide_static.lib
- msbuild RUN_TESTS.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd ..\build-dll
- msbuild RUN_TESTS.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: .\standalone\output\
  name: nowide-vc12-x64
