#!/bin/bash

if [[ -e "nowide/src/iostream.cpp" ]]; then
  exit
fi

rm -fr nowide/nowide
rm -fr nowide/src
rm -fr nowide/test
mkdir nowide/nowide
mkdir nowide/src
mkdir nowide/test

cp ../boost/nowide/*.hpp nowide/nowide
cp ../libs/nowide/src/*.cpp nowide/src
cp ../libs/nowide/test/*.cpp ../libs/nowide/test/*.hpp nowide/test
cp ./*.hpp nowide/nowide/

SOURCES="nowide/test/* nowide/src/* nowide/nowide/*"

case "`uname`" in
  Darwin) echo "Darwin"; sedi="sed -i ''" ;;
  *) echo "Linux"; sedi="sed -i" ;;
esac

$sedi 's/BOOST_NOWIDE_/NOWIDE_/g' $SOURCES
$sedi 's/BOOST_/NOWIDE_/g' $SOURCES
$sedi 's/boost::nowide::/nowide::/g' $SOURCES
$sedi 's/boost::nowide/nowide/g' $SOURCES
$sedi 's/boost::locale::/nowide::/g' $SOURCES
$sedi 's/boost::/nowide::/g' $SOURCES
$sedi 's/namespace boost {//' $SOURCES
$sedi 's/} *\/\/ *namespace boost//' $SOURCES
$sedi 's/<boost\/locale\//<nowide\//g' $SOURCES
$sedi 's/<boost\/nowide\//<nowide\//g' $SOURCES
$sedi 's/<boost\//<nowide\//g' $SOURCES
